const { app, BrowserWindow, ipcMain } = require('electron');
const assert = require('node:assert/strict');
const path = require('node:path');
const data = new Map();
app.disableHardwareAcceleration();
app.on('window-all-closed', () => {});
ipcMain.handle('plugin-storage-get-async', (_event, _plugin, key) => data.get(key) ?? null);
ipcMain.handle('plugin-storage-set-async', (_event, _plugin, key, value) => { data.set(key, structuredClone(value)); return true; });
app.whenReady().then(async () => {
  const dir = path.join(__dirname, '..', 'app', 'software', 'sanrenjz-tools-task-habit');
  const win = new BrowserWindow({ show: false, width: 900, height: 650, webPreferences: { preload: path.join(dir, 'preload.js'), nodeIntegration: true, contextIsolation: false } });
  win.webContents.on('console-message', (_event, level, message) => { if (level >= 2) console.error('renderer:', message); });
  try {
    await win.loadFile(path.join(dir, 'index.html'));
    await win.webContents.executeJavaScript('new Promise(resolve => setTimeout(resolve, 150))');
    const result = await win.webContents.executeJavaScript(`(async () => {
      document.querySelector('#todoInput').value = '完成报告';
      document.querySelector('#todoDue').value = '2026-09-26';
      document.querySelector('#todoAdd').click();
      await new Promise(resolve => setTimeout(resolve, 80));
      document.querySelector('#todoFilter').value = 'all';
      document.querySelector('#todoFilter').dispatchEvent(new Event('change'));
      document.querySelector('[data-edit]').click();
      document.querySelector('#editTitle').value = '完成季度报告';
      document.querySelector('#editForm').requestSubmit();
      await new Promise(resolve => setTimeout(resolve, 80));
      document.querySelector('[data-tog]').click();
      await new Promise(resolve => setTimeout(resolve, 80));
      window.confirm = () => true;
      const imported = new File(['- [ ] 导入的任务\\n- [x] 已完成的导入任务'], 'tasks.md', { type: 'text/markdown' });
      await importFiles([imported]);
      await new Promise(resolve => setTimeout(resolve, 150));
      document.querySelector('[data-tool="habit-tracker"]').click();
      document.querySelector('#habitInput').value = '每天阅读';
      document.querySelector('#habitGoal').value = '5';
      document.querySelector('#habitAdd').click();
      await new Promise(resolve => setTimeout(resolve, 80));
      const today = new Date();
      const key = taskHabitCore.dateKey(today);
      document.querySelector('[data-date="' + key + '"]').click();
      await new Promise(resolve => setTimeout(resolve, 80));
      const futureDisabled = [...document.querySelectorAll('.day-check')].filter(x => x.dataset.date > key).every(x => x.disabled);
      return { title: document.querySelector('.habit-name').textContent, futureDisabled, scroll: document.documentElement.scrollHeight <= innerHeight + 1 };
    })()`);
    assert.ok(data.get('todos').some(task => task.title === '完成季度报告' && task.completed));
    assert.ok(data.get('todos').some(task => task.title === '导入的任务' && !task.completed));
    assert.ok(data.get('todos').some(task => task.title === '已完成的导入任务' && task.completed));
    assert.equal(data.get('habits')[0].weeklyGoal, 5);
    assert.equal(Object.values(data.get('habits')[0].days).filter(Boolean).length, 1);
    assert.equal(result.futureDisabled, true);
    assert.equal(result.scroll, true);
    await win.webContents.executeJavaScript(`(async () => {
      window.confirm = () => true;
      const transfer = new DataTransfer();
      transfer.items.add(new File(['- [ ] 拖入任务\\n- [x] 已完成任务'], 'tasks.md', { type: 'text/markdown' }));
      window.dispatchEvent(new DragEvent('dragenter', { dataTransfer: transfer, bubbles: true }));
      window.dispatchEvent(new DragEvent('drop', { dataTransfer: transfer, bubbles: true }));
      await new Promise(resolve => setTimeout(resolve, 100));
    })()`);
    assert.equal(data.get('todos').length, 5);
    assert.equal(data.get('todos')[0].title, '拖入任务');
    assert.equal(data.get('todos')[1].completed, true);
    win.setSize(1180, 760);
    const larger = await win.webContents.executeJavaScript('document.documentElement.scrollHeight <= innerHeight + 1');
    assert.equal(larger, true);
    win.maximize();
    await new Promise(resolve => setTimeout(resolve, 100));
    const maximized = await win.webContents.executeJavaScript('document.documentElement.scrollHeight <= innerHeight + 1');
    assert.equal(maximized, true);
    await win.webContents.executeJavaScript(`(async () => {
      document.querySelector('[data-tool="todo-list"]').click();
      document.querySelector('#todoFilter').value = 'open';
      document.querySelector('#todoFilter').dispatchEvent(new Event('change'));
      document.querySelector('[data-focus]').click();
      document.querySelector('#focusMinutes').value = '1';
      document.querySelector('#focusMinutes').dispatchEvent(new Event('change'));
      document.querySelector('#timerStart').click();
      await new Promise(resolve => setTimeout(resolve, 100));
    })()`);
    const activeTimer = data.get('pomodoro-v1');
    assert.equal(activeTimer.taskId, data.get('todos').find(task => !task.completed).id);
    activeTimer.runningUntil = Date.now() - 1;
    data.set('pomodoro-v1', activeTimer);
    await win.reload();
    await new Promise(resolve => setTimeout(resolve, 180));
    assert.equal(data.get('pomodoro-v1').sessions.length, 1);
    win.setSize(900, 650);
    const compactFocus = await win.webContents.executeJavaScript(`(() => {
      document.querySelector('[data-tool="pomodoro"]').click();
      return { pageOverflow: document.documentElement.scrollWidth > innerWidth + 1, panelOverflow: document.querySelector('.focus-layout').scrollWidth > document.querySelector('.focus-layout').clientWidth + 1, sessions: document.querySelector('#todayPomos').textContent };
    })()`);
    assert.equal(compactFocus.pageOverflow, false);
    assert.equal(compactFocus.panelOverflow, false);
    assert.equal(compactFocus.sessions, '1');
    assert.equal(data.get('todos').find(task => task.id === activeTimer.taskId).pomodoros, 1);
    assert.equal(data.get('pomodoro-v1').phase, 'shortBreak');
    await win.reload();
    await new Promise(resolve => setTimeout(resolve, 180));
    assert.equal(data.get('pomodoro-v1').sessions.length, 1);
    console.log('task-habit Electron interaction tests passed');
    app.exit(0);
  } catch (error) { console.error(error); app.exit(1); }
  finally { win.destroy(); }
});
