const fs = require('fs');
const path = require('path');
const { createRequire } = require('module');

function loadDatabaseDriver() {
  try {
    return require('better-sqlite3');
  } catch (originalError) {
    if (!process.resourcesPath) throw originalError;
    // 持久化插件位于安装目录 plugins，需从打包主程序的依赖树解析原生模块。
    const appRequire = createRequire(path.join(process.resourcesPath, 'app.asar', 'package.json'));
    return appRequire('better-sqlite3');
  }
}

const Database = loadDatabaseDriver();
const IDENTIFIER_PATTERN = /^[^\u0000-\u001f\u007f]+$/u;
const ALLOWED_COLUMN_TYPES = new Set(['TEXT', 'INTEGER', 'REAL', 'NUMERIC', 'BLOB']);

function quoteIdentifier(value) {
  const identifier = String(value || '').trim();
  if (!identifier || !IDENTIFIER_PATTERN.test(identifier)) throw new Error('名称不能为空或包含控制字符');
  return `"${identifier.replace(/"/g, '""')}"`;
}

function assertDatabasePath(databasePath, allowCreate = false) {
  const resolved = path.resolve(String(databasePath || '').trim());
  if (!allowCreate && !fs.existsSync(resolved)) throw new Error('数据库文件不存在');
  if (allowCreate) fs.mkdirSync(path.dirname(resolved), { recursive: true });
  return resolved;
}

function withDatabase(databasePath, options, callback) {
  const resolved = assertDatabasePath(databasePath, options?.allowCreate === true);
  const database = new Database(resolved, { fileMustExist: options?.allowCreate !== true });
  try {
    database.pragma('busy_timeout = 5000');
    database.pragma('foreign_keys = ON');
    return callback(database, resolved);
  } finally {
    database.close();
  }
}

function getTablesFromDatabase(database) {
  return database.prepare(`
    SELECT name
    FROM sqlite_schema
    WHERE type = 'table' AND name NOT LIKE 'sqlite\\_%' ESCAPE '\\'
    ORDER BY name COLLATE NOCASE
  `).all().map(row => row.name);
}

function assertTable(database, tableName) {
  const tables = getTablesFromDatabase(database);
  if (!tables.includes(tableName)) throw new Error(`数据表不存在：${tableName}`);
}

function getColumnsFromDatabase(database, tableName) {
  assertTable(database, tableName);
  return database.prepare(`
    SELECT cid, name, type, "notnull" AS "notNull", dflt_value AS "defaultValue", pk, hidden
    FROM pragma_table_xinfo(?)
    ORDER BY cid
  `).all(tableName).map(column => ({
    ...column,
    notNull: Boolean(column.notNull),
    primaryKey: Number(column.pk) > 0,
    hidden: Number(column.hidden || 0),
    insertable: Number(column.hidden || 0) === 0,
    autoGenerated: Number(column.pk) > 0 && /^INTEGER$/i.test(String(column.type || '').trim())
  }));
}

function serializeValue(value) {
  if (Buffer.isBuffer(value)) {
    return { __sqliteType: 'blob', byteLength: value.length, base64: value.toString('base64') };
  }
  if (typeof value === 'bigint') return { __sqliteType: 'integer', value: value.toString() };
  return value;
}

function serializeRow(row) {
  return Object.fromEntries(Object.entries(row).map(([key, value]) => [key, serializeValue(value)]));
}

function escapeLike(value) {
  return String(value).replace(/[\\%_]/g, character => `\\${character}`);
}

function coerceValue(column, rawValue) {
  if (rawValue === null) return null;
  const value = String(rawValue);
  const type = String(column.type || '').toUpperCase();
  if (/\bINT\b/.test(type) || type.includes('INT')) {
    if (!/^[+-]?\d+$/.test(value.trim())) throw new Error(`${column.name} 必须是整数`);
    const numeric = Number(value);
    if (!Number.isSafeInteger(numeric)) throw new Error(`${column.name} 超出安全整数范围`);
    return numeric;
  }
  if (/(REAL|FLOA|DOUB|NUMERIC|DECIMAL)/.test(type)) {
    const numeric = Number(value);
    if (!Number.isFinite(numeric)) throw new Error(`${column.name} 必须是数字`);
    return numeric;
  }
  if (type.includes('BOOL')) {
    if (/^(1|true|是|yes)$/i.test(value.trim())) return 1;
    if (/^(0|false|否|no)$/i.test(value.trim())) return 0;
    throw new Error(`${column.name} 必须是 true/false、是/否或 1/0`);
  }
  if (type.includes('BLOB')) return Buffer.from(value, 'utf8');
  if (type.includes('JSON')) {
    try { JSON.parse(value); } catch (_) { throw new Error(`${column.name} 不是有效 JSON`); }
  }
  return value;
}

function inspectDatabase(databasePath) {
  return withDatabase(databasePath, {}, (database, resolved) => ({
    databasePath: resolved,
    tables: getTablesFromDatabase(database)
  }));
}

function getTableSchema(databasePath, tableName) {
  return withDatabase(databasePath, {}, database => ({
    tableName,
    columns: getColumnsFromDatabase(database, tableName)
  }));
}

function queryRows(databasePath, request) {
  const pageSize = Math.min(200, Math.max(10, Number(request.pageSize) || 50));
  const page = Math.max(1, Number(request.page) || 1);
  return withDatabase(databasePath, {}, database => {
    const columns = getColumnsFromDatabase(database, request.tableName);
    const columnNames = columns.filter(column => column.hidden === 0).map(column => column.name);
    if (!columnNames.length) return { columns, rows: [], total: 0, page, pageSize };

    let whereClause = '';
    const parameters = [];
    const searchText = String(request.searchText || '');
    if (searchText && request.searchColumn) {
      const searchAllColumns = request.searchColumn === '__all__';
      if (!searchAllColumns && !columnNames.includes(request.searchColumn)) throw new Error('查询字段不属于当前数据表');
      const searchColumns = searchAllColumns ? columnNames : [request.searchColumn];
      const exactMatch = request.searchMode === 'equals';
      const predicate = searchColumns.map(name => {
        const column = quoteIdentifier(name);
        return exactMatch ? `CAST(${column} AS TEXT) = ?` : `CAST(${column} AS TEXT) LIKE ? ESCAPE '\\'`;
      });
      whereClause = ` WHERE (${predicate.join(' OR ')})`;
      const parameter = exactMatch ? searchText : `%${escapeLike(searchText)}%`;
      parameters.push(...searchColumns.map(() => parameter));
    }

    const table = quoteIdentifier(request.tableName);
    const total = database.prepare(`SELECT COUNT(*) AS count FROM ${table}${whereClause}`).get(...parameters).count;
    const rows = database.prepare(`
      SELECT ${columnNames.map(quoteIdentifier).join(', ')}
      FROM ${table}${whereClause}
      LIMIT ? OFFSET ?
    `).all(...parameters, pageSize, (page - 1) * pageSize).map(serializeRow);
    return { columns, rows, total: Number(total), page, pageSize };
  });
}

function insertRow(databasePath, request) {
  return withDatabase(databasePath, {}, database => {
    const columns = getColumnsFromDatabase(database, request.tableName).filter(column => column.insertable);
    const allowed = new Map(columns.map(column => [column.name, column]));
    const input = request.values && typeof request.values === 'object' ? request.values : {};
    const entries = [];

    for (const [name, rawValue] of Object.entries(input)) {
      const column = allowed.get(name);
      if (!column || column.autoGenerated) continue;
      if (rawValue === undefined || rawValue === '') continue;
      entries.push([name, coerceValue(column, rawValue)]);
    }

    for (const column of columns) {
      if (column.autoGenerated || !column.notNull || column.defaultValue !== null) continue;
      if (!entries.some(([name]) => name === column.name)) throw new Error(`${column.name} 为必填字段`);
    }

    const table = quoteIdentifier(request.tableName);
    let result;
    if (!entries.length) {
      result = database.prepare(`INSERT INTO ${table} DEFAULT VALUES`).run();
    } else {
      const names = entries.map(([name]) => quoteIdentifier(name)).join(', ');
      const placeholders = entries.map(() => '?').join(', ');
      result = database.prepare(`INSERT INTO ${table} (${names}) VALUES (${placeholders})`).run(...entries.map(([, value]) => value));
    }
    return { changes: result.changes, lastInsertRowid: String(result.lastInsertRowid) };
  });
}

function createDatabase(databasePath) {
  return withDatabase(databasePath, { allowCreate: true }, (_database, resolved) => ({ databasePath: resolved, tables: [] }));
}

function createTable(databasePath, request) {
  const tableName = String(request.tableName || '').trim();
  const columns = Array.isArray(request.columns) ? request.columns : [];
  if (!tableName) throw new Error('请输入数据表名称');
  if (!columns.length) throw new Error('请至少添加一个字段');
  const seen = new Set();
  const definitions = columns.map(column => {
    const name = String(column.name || '').trim();
    if (!name) throw new Error('字段名称不能为空');
    if (seen.has(name.toLocaleLowerCase())) throw new Error(`字段名称重复：${name}`);
    seen.add(name.toLocaleLowerCase());
    const type = String(column.type || 'TEXT').toUpperCase();
    if (!ALLOWED_COLUMN_TYPES.has(type)) throw new Error(`不支持的字段类型：${type}`);
    if (column.primaryKey) {
      if (type !== 'INTEGER') throw new Error('自动主键必须使用 INTEGER 类型');
      return `${quoteIdentifier(name)} INTEGER PRIMARY KEY AUTOINCREMENT`;
    }
    return `${quoteIdentifier(name)} ${type}${column.notNull ? ' NOT NULL' : ''}`;
  });
  if (columns.filter(column => column.primaryKey).length > 1) throw new Error('只能设置一个自动主键');

  return withDatabase(databasePath, {}, database => {
    if (getTablesFromDatabase(database).includes(tableName)) throw new Error(`数据表已存在：${tableName}`);
    database.prepare(`CREATE TABLE ${quoteIdentifier(tableName)} (${definitions.join(', ')})`).run();
    return { tableName, columns: getColumnsFromDatabase(database, tableName) };
  });
}

module.exports = {
  inspectDatabase,
  getTableSchema,
  queryRows,
  insertRow,
  createDatabase,
  createTable,
  quoteIdentifier
};
