const fs = require('fs');
const path = require('path');
const { createRequire } = require('module');

function loadDatabaseDriver() {
  try {
    return require('better-sqlite3');
  } catch (originalError) {
    if (!process.resourcesPath) throw originalError;
    // 持久化插件位于安装目录 plugins，需从打包主程序的依赖树解析原生模块。
    const appRequire = createRequire(path.join(process.resourcesPath, 'app.asar', 'package.json'));
    return appRequire('better-sqlite3');
  }
}

const Database = loadDatabaseDriver();
const IDENTIFIER_PATTERN = /^[^\u0000-\u001f\u007f]+$/u;
const ALLOWED_COLUMN_TYPES = new Set(['TEXT', 'INTEGER', 'REAL', 'NUMERIC', 'BLOB']);

function quoteIdentifier(value) {
  const identifier = String(value || '').trim();
  if (!identifier || !IDENTIFIER_PATTERN.test(identifier)) throw new Error('名称不能为空或包含控制字符');
  return `"${identifier.replace(/"/g, '""')}"`;
}

function assertDatabasePath(databasePath, allowCreate = false) {
  const resolved = path.resolve(String(databasePath || '').trim());
  if (!allowCreate && !fs.existsSync(resolved)) throw new Error('数据库文件不存在');
  if (allowCreate) fs.mkdirSync(path.dirname(resolved), { recursive: true });
  return resolved;
}

function withDatabase(databasePath, options, callback) {
  const resolved = assertDatabasePath(databasePath, options?.allowCreate === true);
  const database = new Database(resolved, { fileMustExist: options?.allowCreate !== true });
  try {
    database.pragma('busy_timeout = 5000');
    database.pragma('foreign_keys = ON');
    return callback(database, resolved);
  } finally {
    database.close();
  }
}

function getTablesFromDatabase(database) {
  return database.prepare(`
    SELECT name
    FROM sqlite_schema
    WHERE type = 'table' AND name NOT LIKE 'sqlite\\_%' ESCAPE '\\'
    ORDER BY name COLLATE NOCASE
  `).all().map(row => row.name);
}

function assertTable(database, tableName) {
  const tables = getTablesFromDatabase(database);
  if (!tables.includes(tableName)) throw new Error(`数据表不存在：${tableName}`);
}

function getColumnsFromDatabase(database, tableName) {
  assertTable(database, tableName);
  const columns = database.prepare(`
    SELECT cid, name, type, "notnull" AS "notNull", dflt_value AS "defaultValue", pk, hidden
    FROM pragma_table_xinfo(?)
    ORDER BY cid
  `).all(tableName);
  const tableSql = database.prepare("SELECT sql FROM sqlite_schema WHERE type = 'table' AND name = ?").get(tableName)?.sql || '';
  const primaryKeys = columns.filter(column => Number(column.pk) > 0);
  const rowidPrimaryKey = primaryKeys.length === 1
    && /^INTEGER$/i.test(String(primaryKeys[0].type || '').trim())
    && !/\bWITHOUT\s+ROWID\b/i.test(tableSql);
  return columns.map(column => ({
    ...column,
    notNull: Boolean(column.notNull),
    primaryKey: Number(column.pk) > 0,
    hidden: Number(column.hidden || 0),
    insertable: Number(column.hidden || 0) === 0,
    autoGenerated: rowidPrimaryKey && Number(column.pk) > 0
  }));
}

function serializeValue(value) {
  if (Buffer.isBuffer(value)) {
    return { __sqliteType: 'blob', byteLength: value.length, base64: value.toString('base64') };
  }
  if (typeof value === 'bigint') return { __sqliteType: 'integer', value: value.toString() };
  return value;
}

function serializeRow(row) {
  return Object.fromEntries(Object.entries(row).map(([key, value]) => [key, serializeValue(value)]));
}

function deserializeValue(value) {
  if (value && value.__sqliteType === 'blob') return Buffer.from(value.base64 || '', 'base64');
  if (value && value.__sqliteType === 'integer') return BigInt(value.value);
  return value;
}

function getEditCapability(database, tableName, columns) {
  const primaryKeys = columns
    .filter(column => column.primaryKey)
    .sort((left, right) => Number(left.pk) - Number(right.pk));
  if (primaryKeys.length) {
    return { editable: true, locatorType: 'primaryKey', locatorColumns: primaryKeys.map(column => column.name) };
  }

  const tableSql = database.prepare("SELECT sql FROM sqlite_schema WHERE type = 'table' AND name = ?").get(tableName)?.sql || '';
  if (/\bWITHOUT\s+ROWID\b/i.test(tableSql)) {
    return { editable: false, reason: '该表没有可用于安全定位记录的主键' };
  }

  // SQLite 允许真实列遮蔽 rowid 别名，只能选择未被占用的内置别名。
  const declaredNames = new Set(columns.map(column => String(column.name).toLocaleLowerCase()));
  const rowidExpression = ['rowid', '_rowid_', 'oid'].find(name => !declaredNames.has(name));
  if (!rowidExpression) return { editable: false, reason: '该表没有可用于安全定位记录的主键或 rowid' };
  let rowidAlias = '__accountManagerRowid';
  while (declaredNames.has(rowidAlias.toLocaleLowerCase())) rowidAlias += '_';
  return { editable: true, locatorType: 'rowid', rowidExpression, rowidAlias };
}

function createLocator(capability, row) {
  if (capability.locatorType === 'primaryKey') {
    return {
      type: 'primaryKey',
      values: capability.locatorColumns.map(name => ({ name, value: serializeValue(row[name]) }))
    };
  }
  return { type: 'rowid', value: serializeValue(row[capability.rowidAlias]) };
}

function buildRecordCondition(capability, visibleColumns, request) {
  const locator = request.locator;
  const whereParts = [];
  const whereValues = [];
  if (capability.locatorType === 'primaryKey') {
    if (locator?.type !== 'primaryKey' || !Array.isArray(locator.values)) throw new Error('记录主键定位信息无效，请刷新后重试');
    const locatorMap = new Map(locator.values.map(item => [item.name, item.value]));
    for (const name of capability.locatorColumns) {
      if (!locatorMap.has(name)) throw new Error('记录主键定位信息不完整，请刷新后重试');
      whereParts.push(`${quoteIdentifier(name)} IS ?`);
      whereValues.push(deserializeValue(locatorMap.get(name)));
    }
  } else {
    if (locator?.type !== 'rowid') throw new Error('记录 rowid 定位信息无效，请刷新后重试');
    whereParts.push(`${capability.rowidExpression} IS ?`);
    whereValues.push(deserializeValue(locator.value));
  }

  // 修改和删除共用原始快照校验，避免外部程序更新后误操作旧记录。
  const original = request.original && typeof request.original === 'object' ? request.original : null;
  if (!original) throw new Error('缺少原始记录快照，请刷新后重试');
  for (const column of visibleColumns) {
    if (!Object.prototype.hasOwnProperty.call(original, column.name)) throw new Error('原始记录快照不完整，请刷新后重试');
    whereParts.push(`${quoteIdentifier(column.name)} IS ?`);
    whereValues.push(deserializeValue(original[column.name]));
  }
  return { whereClause: whereParts.join(' AND '), whereValues };
}

function escapeLike(value) {
  return String(value).replace(/[\\%_]/g, character => `\\${character}`);
}

function coerceValue(column, rawValue) {
  if (rawValue === null) return null;
  const value = String(rawValue);
  const type = String(column.type || '').toUpperCase();
  if (/\bINT\b/.test(type) || type.includes('INT')) {
    if (!/^[+-]?\d+$/.test(value.trim())) throw new Error(`${column.name} 必须是整数`);
    const numeric = Number(value);
    if (!Number.isSafeInteger(numeric)) throw new Error(`${column.name} 超出安全整数范围`);
    return numeric;
  }
  if (/(REAL|FLOA|DOUB|NUMERIC|DECIMAL)/.test(type)) {
    const numeric = Number(value);
    if (!Number.isFinite(numeric)) throw new Error(`${column.name} 必须是数字`);
    return numeric;
  }
  if (type.includes('BOOL')) {
    if (/^(1|true|是|yes)$/i.test(value.trim())) return 1;
    if (/^(0|false|否|no)$/i.test(value.trim())) return 0;
    throw new Error(`${column.name} 必须是 true/false、是/否或 1/0`);
  }
  if (type.includes('BLOB')) return Buffer.from(value, 'utf8');
  if (type.includes('JSON')) {
    try { JSON.parse(value); } catch (_) { throw new Error(`${column.name} 不是有效 JSON`); }
  }
  return value;
}

function inspectDatabase(databasePath) {
  return withDatabase(databasePath, {}, (database, resolved) => ({
    databasePath: resolved,
    tables: getTablesFromDatabase(database)
  }));
}

function getTableSchema(databasePath, tableName) {
  return withDatabase(databasePath, {}, database => ({
    tableName,
    columns: getColumnsFromDatabase(database, tableName)
  }));
}

function queryRows(databasePath, request) {
  const pageSize = Math.min(200, Math.max(10, Number(request.pageSize) || 50));
  const page = Math.max(1, Number(request.page) || 1);
  return withDatabase(databasePath, {}, database => {
    const columns = getColumnsFromDatabase(database, request.tableName);
    const columnNames = columns.filter(column => column.hidden === 0).map(column => column.name);
    const editCapability = getEditCapability(database, request.tableName, columns);
    if (!columnNames.length) return { columns, rows: [], total: 0, page, pageSize, editCapability };

    let whereClause = '';
    const parameters = [];
    const searchText = String(request.searchText || '');
    if (searchText && request.searchColumn) {
      const searchAllColumns = request.searchColumn === '__all__';
      if (!searchAllColumns && !columnNames.includes(request.searchColumn)) throw new Error('查询字段不属于当前数据表');
      const searchColumns = searchAllColumns ? columnNames : [request.searchColumn];
      const exactMatch = request.searchMode === 'equals';
      const predicate = searchColumns.map(name => {
        const column = quoteIdentifier(name);
        return exactMatch ? `CAST(${column} AS TEXT) = ?` : `CAST(${column} AS TEXT) LIKE ? ESCAPE '\\'`;
      });
      whereClause = ` WHERE (${predicate.join(' OR ')})`;
      const parameter = exactMatch ? searchText : `%${escapeLike(searchText)}%`;
      parameters.push(...searchColumns.map(() => parameter));
    }

    const table = quoteIdentifier(request.tableName);
    const total = database.prepare(`SELECT COUNT(*) AS count FROM ${table}${whereClause}`).get(...parameters).count;
    const locatorSelection = editCapability.locatorType === 'rowid'
      ? `, ${editCapability.rowidExpression} AS ${quoteIdentifier(editCapability.rowidAlias)}`
      : '';
    const rows = database.prepare(`
      SELECT ${columnNames.map(quoteIdentifier).join(', ')}${locatorSelection}
      FROM ${table}${whereClause}
      LIMIT ? OFFSET ?
    `).all(...parameters, pageSize, (page - 1) * pageSize).map(row => {
      const locator = editCapability.editable ? createLocator(editCapability, row) : null;
      if (editCapability.rowidAlias) delete row[editCapability.rowidAlias];
      const serialized = serializeRow(row);
      return { ...serialized, __locator: locator, __original: serialized };
    });
    return { columns, rows, total: Number(total), page, pageSize, editCapability };
  });
}

function insertRow(databasePath, request) {
  return withDatabase(databasePath, {}, database => {
    const columns = getColumnsFromDatabase(database, request.tableName).filter(column => column.insertable);
    const allowed = new Map(columns.map(column => [column.name, column]));
    const input = request.values && typeof request.values === 'object' ? request.values : {};
    const entries = [];

    for (const [name, rawValue] of Object.entries(input)) {
      const column = allowed.get(name);
      if (!column || column.autoGenerated) continue;
      if (rawValue === undefined || rawValue === '') continue;
      entries.push([name, coerceValue(column, rawValue)]);
    }

    for (const column of columns) {
      if (column.autoGenerated || !column.notNull || column.defaultValue !== null) continue;
      if (!entries.some(([name]) => name === column.name)) throw new Error(`${column.name} 为必填字段`);
    }

    const table = quoteIdentifier(request.tableName);
    let result;
    if (!entries.length) {
      result = database.prepare(`INSERT INTO ${table} DEFAULT VALUES`).run();
    } else {
      const names = entries.map(([name]) => quoteIdentifier(name)).join(', ');
      const placeholders = entries.map(() => '?').join(', ');
      result = database.prepare(`INSERT INTO ${table} (${names}) VALUES (${placeholders})`).run(...entries.map(([, value]) => value));
    }
    return { changes: result.changes, lastInsertRowid: String(result.lastInsertRowid) };
  });
}

function updateRow(databasePath, request) {
  return withDatabase(databasePath, {}, database => {
    const columns = getColumnsFromDatabase(database, request.tableName);
    const visibleColumns = columns.filter(column => column.hidden === 0);
    const allowed = new Map(visibleColumns.filter(column => column.insertable && !column.autoGenerated).map(column => [column.name, column]));
    const capability = getEditCapability(database, request.tableName, columns);
    if (!capability.editable) throw new Error(capability.reason || '当前数据表不支持安全修改');

    const input = request.values && typeof request.values === 'object' ? request.values : {};
    const entries = [];
    for (const [name, rawValue] of Object.entries(input)) {
      const column = allowed.get(name);
      if (!column) continue;
      if (rawValue === null && column.notNull) throw new Error(`${column.name} 不允许设为 NULL`);
      entries.push([name, coerceValue(column, rawValue)]);
    }
    if (!entries.length) throw new Error('没有可修改的字段');

    const { whereClause, whereValues } = buildRecordCondition(capability, visibleColumns, request);

    const setClause = entries.map(([name]) => `${quoteIdentifier(name)} = ?`).join(', ');
    const setValues = entries.map(([, value]) => value);
    return database.transaction(() => {
      const result = database.prepare(`
        UPDATE ${quoteIdentifier(request.tableName)}
        SET ${setClause}
        WHERE ${whereClause}
      `).run(...setValues, ...whereValues);
      if (result.changes !== 1) throw new Error('记录已被修改或删除，或无法唯一定位，请刷新数据后重新编辑');
      return { changes: result.changes };
    })();
  });
}

function deleteRow(databasePath, request) {
  return withDatabase(databasePath, {}, database => {
    const columns = getColumnsFromDatabase(database, request.tableName);
    const visibleColumns = columns.filter(column => column.hidden === 0);
    const capability = getEditCapability(database, request.tableName, columns);
    if (!capability.editable) throw new Error(capability.reason || '当前数据表不支持安全删除');
    const { whereClause, whereValues } = buildRecordCondition(capability, visibleColumns, request);
    return database.transaction(() => {
      const result = database.prepare(`DELETE FROM ${quoteIdentifier(request.tableName)} WHERE ${whereClause}`).run(...whereValues);
      if (result.changes !== 1) throw new Error('记录已被修改或删除，或无法唯一定位，请刷新数据后重试');
      return { changes: result.changes };
    })();
  });
}

function createDatabase(databasePath) {
  return withDatabase(databasePath, { allowCreate: true }, (_database, resolved) => ({ databasePath: resolved, tables: [] }));
}

function createTable(databasePath, request) {
  const tableName = String(request.tableName || '').trim();
  const columns = Array.isArray(request.columns) ? request.columns : [];
  if (!tableName) throw new Error('请输入数据表名称');
  if (!columns.length) throw new Error('请至少添加一个字段');
  const seen = new Set();
  const definitions = columns.map(column => {
    const name = String(column.name || '').trim();
    if (!name) throw new Error('字段名称不能为空');
    if (seen.has(name.toLocaleLowerCase())) throw new Error(`字段名称重复：${name}`);
    seen.add(name.toLocaleLowerCase());
    const type = String(column.type || 'TEXT').toUpperCase();
    if (!ALLOWED_COLUMN_TYPES.has(type)) throw new Error(`不支持的字段类型：${type}`);
    if (column.primaryKey) {
      if (type !== 'INTEGER') throw new Error('自动主键必须使用 INTEGER 类型');
      return `${quoteIdentifier(name)} INTEGER PRIMARY KEY AUTOINCREMENT`;
    }
    return `${quoteIdentifier(name)} ${type}${column.notNull ? ' NOT NULL' : ''}`;
  });
  if (columns.filter(column => column.primaryKey).length > 1) throw new Error('只能设置一个自动主键');

  return withDatabase(databasePath, {}, database => {
    if (getTablesFromDatabase(database).includes(tableName)) throw new Error(`数据表已存在：${tableName}`);
    database.prepare(`CREATE TABLE ${quoteIdentifier(tableName)} (${definitions.join(', ')})`).run();
    return { tableName, columns: getColumnsFromDatabase(database, tableName) };
  });
}

module.exports = {
  inspectDatabase,
  getTableSchema,
  queryRows,
  insertRow,
  updateRow,
  deleteRow,
  createDatabase,
  createTable,
  quoteIdentifier
};
